### ISSUE TITLE
Implementation of the design on the MEapp on IOS

### ISSUE THREAD

**Issue by TomForus** [teamforus/concept-identity#10]
# Implementation of the design on the MEapp on IOS

## Sort of Issue

Enhancement

## Prerequisites

1. Finish the functionality of the native IOS MEapp
2. Finish the designs of the  native IOS MEapp

## Description

The implementation of the new designs made by @danrminds and @dev-weget in the native IOS ME application made by @jamalv 

## Functional Design (Enhancement)

1. Insert ME-view (home-screen)
2. Insert Wallet-view
3. Insert records-view
4. Insert new-users views

**User Story:** The new designs of the MEapp should be fully functional on the native IOS MEapp

**Comment by jamalv** [comment]
Closing this issue for now since it is not relevant yet. The native apps should first focus on functionality, while the demo app focuses on design and UX. This way we make progress the fastest, keeping the design the most flexible without having to perform each change for three platforms. Will re-open the issue when the designs are ready to be implemented.
